AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GatewayRouterLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/gateway-router-trigger.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          GATEWAY_ROUTER_URL: !Ref GatewayRouterUrl
  WebhookNotifierLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/webhook-notifier-trigger.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          WEBHOOK_NOTIFIER_URL: !Ref WebhookNotifierUrl
Parameters:
  GatewayRouterUrl:
    Type: String
  WebhookNotifierUrl:
    Type: String
